[package]
name = "asciifier"
version = "0.1.0"
edition = "2021"


[dependencies]
image = { version = "0.25.4" }
ansi_rgb = "0.2.0"
rgb = "0.8.50"
ttf-parser = "0.25.0"
base64 = "0.22.1"
ab_glyph = "0.2.29"
palette = "0.7.6"
enterpolation = "0.2.1"
